// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function CreateBackup():Promise<main.BackupInfo>;

export function GetDatabaseInfo():Promise<main.BackupInfo>;

export function RestoreBackup():Promise<main.BackupInfo>;

export function SetContext(arg1:context.Context):Promise<void>;
