// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup() {
  return window['go']['main']['BackupService']['CreateBackup']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['BackupService']['GetDatabaseInfo']();
}

export function RestoreBackup() {
  return window['go']['main']['BackupService']['RestoreBackup']();
}

export function SetContext(arg1) {
  return window['go']['main']['BackupService']['SetContext'](arg1);
}
