// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBreedingRecord(arg1:main.BreedingRecord):Promise<number>;

export function DeleteBreedingRecord(arg1:number):Promise<void>;

export function GetAllBreedingRecords():Promise<Array<main.BreedingRecord>>;

export function GetBreedingHistoryForAnimal(arg1:number):Promise<Array<main.BreedingRecord>>;

export function GetBreedingRecord(arg1:number):Promise<main.BreedingRecord>;

export function GetPregnantAnimals():Promise<Array<main.BreedingRecord>>;

export function RecordBirth(arg1:number,arg2:number,arg3:string):Promise<void>;

export function UpdateBreedingRecord(arg1:main.BreedingRecord):Promise<void>;

export function UpdatePregnancyStatus(arg1:number,arg2:string):Promise<void>;
