// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBreedingRecord(arg1) {
  return window['go']['main']['BreedingService']['AddBreedingRecord'](arg1);
}

export function DeleteBreedingRecord(arg1) {
  return window['go']['main']['BreedingService']['DeleteBreedingRecord'](arg1);
}

export function GetAllBreedingRecords() {
  return window['go']['main']['BreedingService']['GetAllBreedingRecords']();
}

export function GetBreedingHistoryForAnimal(arg1) {
  return window['go']['main']['BreedingService']['GetBreedingHistoryForAnimal'](arg1);
}

export function GetBreedingRecord(arg1) {
  return window['go']['main']['BreedingService']['GetBreedingRecord'](arg1);
}

export function GetPregnantAnimals() {
  return window['go']['main']['BreedingService']['GetPregnantAnimals']();
}

export function RecordBirth(arg1, arg2, arg3) {
  return window['go']['main']['BreedingService']['RecordBirth'](arg1, arg2, arg3);
}

export function UpdateBreedingRecord(arg1) {
  return window['go']['main']['BreedingService']['UpdateBreedingRecord'](arg1);
}

export function UpdatePregnancyStatus(arg1, arg2) {
  return window['go']['main']['BreedingService']['UpdatePregnancyStatus'](arg1, arg2);
}
