// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCropRecord(arg1) {
  return window['go']['main']['CropsService']['AddCropRecord'](arg1);
}

export function AddField(arg1) {
  return window['go']['main']['CropsService']['AddField'](arg1);
}

export function DeleteCropRecord(arg1) {
  return window['go']['main']['CropsService']['DeleteCropRecord'](arg1);
}

export function DeleteField(arg1) {
  return window['go']['main']['CropsService']['DeleteField'](arg1);
}

export function GetActiveCropsCount() {
  return window['go']['main']['CropsService']['GetActiveCropsCount']();
}

export function GetAllFields() {
  return window['go']['main']['CropsService']['GetAllFields']();
}

export function GetCropRecords(arg1) {
  return window['go']['main']['CropsService']['GetCropRecords'](arg1);
}

export function GetField(arg1) {
  return window['go']['main']['CropsService']['GetField'](arg1);
}

export function GetKenyanCropTypes() {
  return window['go']['main']['CropsService']['GetKenyanCropTypes']();
}

export function GetTotalFieldsAcres() {
  return window['go']['main']['CropsService']['GetTotalFieldsAcres']();
}

export function UpdateCropRecord(arg1) {
  return window['go']['main']['CropsService']['UpdateCropRecord'](arg1);
}

export function UpdateField(arg1) {
  return window['go']['main']['CropsService']['UpdateField'](arg1);
}
