// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCropRecord(arg1:main.CropRecord):Promise<number>;

export function AddField(arg1:main.Field):Promise<number>;

export function DeleteCropRecord(arg1:number):Promise<void>;

export function DeleteField(arg1:number):Promise<void>;

export function GetActiveCropsCount():Promise<number>;

export function GetAllFields():Promise<Array<main.Field>>;

export function GetCropRecords(arg1:number):Promise<Array<main.CropRecord>>;

export function GetField(arg1:number):Promise<main.Field>;

export function GetKenyanCropTypes():Promise<Array<string>>;

export function GetTotalFieldsAcres():Promise<number>;

export function UpdateCropRecord(arg1:main.CropRecord):Promise<void>;

export function UpdateField(arg1:main.Field):Promise<void>;
