// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardStats() {
  return window['go']['main']['DashboardService']['GetDashboardStats']();
}

export function GetMilkProductionChart() {
  return window['go']['main']['DashboardService']['GetMilkProductionChart']();
}

export function GetRecentActivity() {
  return window['go']['main']['DashboardService']['GetRecentActivity']();
}
