// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetMilkProductionChart():Promise<Array<Record<string, any>>>;

export function GetRecentActivity():Promise<Array<main.RecentActivity>>;
