// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function ExportAnimalsCSV():Promise<main.ExportResult>;

export function GetExportDirectory():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
