// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAnimalsCSV() {
  return window['go']['main']['ExportService']['ExportAnimalsCSV']();
}

export function GetExportDirectory() {
  return window['go']['main']['ExportService']['GetExportDirectory']();
}

export function SetContext(arg1) {
  return window['go']['main']['ExportService']['SetContext'](arg1);
}
