// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFeedRecord(arg1:main.FeedRecord):Promise<number>;

export function AddFeedType(arg1:main.FeedType):Promise<number>;

export function DeleteFeedRecord(arg1:number):Promise<void>;

export function DeleteFeedType(arg1:number):Promise<void>;

export function GetAllFeedTypes():Promise<Array<main.FeedType>>;

export function GetFeedRecords(arg1:string,arg2:string):Promise<Array<main.FeedRecord>>;

export function UpdateFeedRecord(arg1:main.FeedRecord):Promise<void>;

export function UpdateFeedType(arg1:main.FeedType):Promise<void>;
