// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFeedRecord(arg1) {
  return window['go']['main']['FeedService']['AddFeedRecord'](arg1);
}

export function AddFeedType(arg1) {
  return window['go']['main']['FeedService']['AddFeedType'](arg1);
}

export function DeleteFeedRecord(arg1) {
  return window['go']['main']['FeedService']['DeleteFeedRecord'](arg1);
}

export function DeleteFeedType(arg1) {
  return window['go']['main']['FeedService']['DeleteFeedType'](arg1);
}

export function GetAllFeedTypes() {
  return window['go']['main']['FeedService']['GetAllFeedTypes']();
}

export function GetFeedRecords(arg1, arg2) {
  return window['go']['main']['FeedService']['GetFeedRecords'](arg1, arg2);
}

export function UpdateFeedRecord(arg1) {
  return window['go']['main']['FeedService']['UpdateFeedRecord'](arg1);
}

export function UpdateFeedType(arg1) {
  return window['go']['main']['FeedService']['UpdateFeedType'](arg1);
}
