// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTransaction(arg1) {
  return window['go']['main']['FinancialService']['AddTransaction'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['FinancialService']['DeleteTransaction'](arg1);
}

export function GetExpenseCategories() {
  return window['go']['main']['FinancialService']['GetExpenseCategories']();
}

export function GetFinancialSummary(arg1, arg2) {
  return window['go']['main']['FinancialService']['GetFinancialSummary'](arg1, arg2);
}

export function GetIncomeCategories() {
  return window['go']['main']['FinancialService']['GetIncomeCategories']();
}

export function GetMonthlyExpenses() {
  return window['go']['main']['FinancialService']['GetMonthlyExpenses']();
}

export function GetMonthlyIncome() {
  return window['go']['main']['FinancialService']['GetMonthlyIncome']();
}

export function GetTransactions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FinancialService']['GetTransactions'](arg1, arg2, arg3, arg4);
}

export function UpdateTransaction(arg1) {
  return window['go']['main']['FinancialService']['UpdateTransaction'](arg1);
}
