// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTransaction(arg1:main.Transaction):Promise<number>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetExpenseCategories():Promise<Array<string>>;

export function GetFinancialSummary(arg1:string,arg2:string):Promise<main.FinancialSummary>;

export function GetIncomeCategories():Promise<Array<string>>;

export function GetMonthlyExpenses():Promise<number>;

export function GetMonthlyIncome():Promise<number>;

export function GetTransactions(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.Transaction>>;

export function UpdateTransaction(arg1:main.Transaction):Promise<void>;
