// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddVetRecord(arg1:main.VetRecord):Promise<number>;

export function DeleteVetRecord(arg1:number):Promise<void>;

export function GetCommonMedicines():Promise<Array<string>>;

export function GetPendingVetVisitsCount():Promise<number>;

export function GetRecordTypes():Promise<Array<string>>;

export function GetUpcomingVaccinations():Promise<Array<main.VetRecord>>;

export function GetVetRecords(arg1:number):Promise<Array<main.VetRecord>>;

export function UpdateVetRecord(arg1:main.VetRecord):Promise<void>;
