// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVetRecord(arg1) {
  return window['go']['main']['HealthService']['AddVetRecord'](arg1);
}

export function DeleteVetRecord(arg1) {
  return window['go']['main']['HealthService']['DeleteVetRecord'](arg1);
}

export function GetCommonMedicines() {
  return window['go']['main']['HealthService']['GetCommonMedicines']();
}

export function GetPendingVetVisitsCount() {
  return window['go']['main']['HealthService']['GetPendingVetVisitsCount']();
}

export function GetRecordTypes() {
  return window['go']['main']['HealthService']['GetRecordTypes']();
}

export function GetUpcomingVaccinations() {
  return window['go']['main']['HealthService']['GetUpcomingVaccinations']();
}

export function GetVetRecords(arg1) {
  return window['go']['main']['HealthService']['GetVetRecords'](arg1);
}

export function UpdateVetRecord(arg1) {
  return window['go']['main']['HealthService']['UpdateVetRecord'](arg1);
}
