// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddInventoryItem(arg1:main.InventoryItem):Promise<number>;

export function DeleteInventoryItem(arg1:number):Promise<void>;

export function GetAllInventory():Promise<Array<main.InventoryItem>>;

export function GetInventoryByCategory(arg1:string):Promise<Array<main.InventoryItem>>;

export function GetInventoryCategories():Promise<Array<string>>;

export function GetLowStockCount():Promise<number>;

export function GetLowStockItems():Promise<Array<main.InventoryItem>>;

export function UpdateInventoryItem(arg1:main.InventoryItem):Promise<void>;

export function UpdateStock(arg1:number,arg2:number):Promise<void>;
