// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInventoryItem(arg1) {
  return window['go']['main']['InventoryService']['AddInventoryItem'](arg1);
}

export function DeleteInventoryItem(arg1) {
  return window['go']['main']['InventoryService']['DeleteInventoryItem'](arg1);
}

export function GetAllInventory() {
  return window['go']['main']['InventoryService']['GetAllInventory']();
}

export function GetInventoryByCategory(arg1) {
  return window['go']['main']['InventoryService']['GetInventoryByCategory'](arg1);
}

export function GetInventoryCategories() {
  return window['go']['main']['InventoryService']['GetInventoryCategories']();
}

export function GetLowStockCount() {
  return window['go']['main']['InventoryService']['GetLowStockCount']();
}

export function GetLowStockItems() {
  return window['go']['main']['InventoryService']['GetLowStockItems']();
}

export function UpdateInventoryItem(arg1) {
  return window['go']['main']['InventoryService']['UpdateInventoryItem'](arg1);
}

export function UpdateStock(arg1, arg2) {
  return window['go']['main']['InventoryService']['UpdateStock'](arg1, arg2);
}
