// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAnimal(arg1:main.Animal):Promise<number>;

export function AddMilkRecord(arg1:main.MilkRecord):Promise<number>;

export function AddMilkSale(arg1:main.MilkSale):Promise<number>;

export function DeleteAnimal(arg1:number):Promise<void>;

export function DeleteMilkRecord(arg1:number):Promise<void>;

export function DeleteMilkSale(arg1:number):Promise<void>;

export function GetAllAnimals():Promise<Array<main.Animal>>;

export function GetAnimal(arg1:number):Promise<main.Animal>;

export function GetDairyCows():Promise<Array<main.Animal>>;

export function GetFemaleAnimals():Promise<Array<main.Animal>>;

export function GetMaleAnimals():Promise<Array<main.Animal>>;

export function GetMilkRecordByAnimalAndDate(arg1:number,arg2:string):Promise<main.MilkRecord>;

export function GetMilkRecords(arg1:number,arg2:string,arg3:string):Promise<Array<main.MilkRecord>>;

export function GetMilkSales(arg1:string,arg2:string):Promise<Array<main.MilkSale>>;

export function GetMonthMilkTotal():Promise<number>;

export function GetOffspring(arg1:number):Promise<Array<main.Animal>>;

export function GetTodayMilkTotal():Promise<number>;

export function UpdateAnimal(arg1:main.Animal):Promise<void>;

export function UpdateMilkRecord(arg1:main.MilkRecord):Promise<void>;

export function UpdateMilkSale(arg1:main.MilkSale):Promise<void>;
