// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAnimal(arg1) {
  return window['go']['main']['LivestockService']['AddAnimal'](arg1);
}

export function AddMilkRecord(arg1) {
  return window['go']['main']['LivestockService']['AddMilkRecord'](arg1);
}

export function AddMilkSale(arg1) {
  return window['go']['main']['LivestockService']['AddMilkSale'](arg1);
}

export function DeleteAnimal(arg1) {
  return window['go']['main']['LivestockService']['DeleteAnimal'](arg1);
}

export function DeleteMilkRecord(arg1) {
  return window['go']['main']['LivestockService']['DeleteMilkRecord'](arg1);
}

export function DeleteMilkSale(arg1) {
  return window['go']['main']['LivestockService']['DeleteMilkSale'](arg1);
}

export function GetAllAnimals() {
  return window['go']['main']['LivestockService']['GetAllAnimals']();
}

export function GetAnimal(arg1) {
  return window['go']['main']['LivestockService']['GetAnimal'](arg1);
}

export function GetDairyCows() {
  return window['go']['main']['LivestockService']['GetDairyCows']();
}

export function GetFemaleAnimals() {
  return window['go']['main']['LivestockService']['GetFemaleAnimals']();
}

export function GetMaleAnimals() {
  return window['go']['main']['LivestockService']['GetMaleAnimals']();
}

export function GetMilkRecordByAnimalAndDate(arg1, arg2) {
  return window['go']['main']['LivestockService']['GetMilkRecordByAnimalAndDate'](arg1, arg2);
}

export function GetMilkRecords(arg1, arg2, arg3) {
  return window['go']['main']['LivestockService']['GetMilkRecords'](arg1, arg2, arg3);
}

export function GetMilkSales(arg1, arg2) {
  return window['go']['main']['LivestockService']['GetMilkSales'](arg1, arg2);
}

export function GetMonthMilkTotal() {
  return window['go']['main']['LivestockService']['GetMonthMilkTotal']();
}

export function GetOffspring(arg1) {
  return window['go']['main']['LivestockService']['GetOffspring'](arg1);
}

export function GetTodayMilkTotal() {
  return window['go']['main']['LivestockService']['GetTodayMilkTotal']();
}

export function UpdateAnimal(arg1) {
  return window['go']['main']['LivestockService']['UpdateAnimal'](arg1);
}

export function UpdateMilkRecord(arg1) {
  return window['go']['main']['LivestockService']['UpdateMilkRecord'](arg1);
}

export function UpdateMilkSale(arg1) {
  return window['go']['main']['LivestockService']['UpdateMilkSale'](arg1);
}
