// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function CheckAndNotify():Promise<void>;

export function GetAllNotifications():Promise<Array<main.Reminder>>;

export function GetLowStockAlerts():Promise<Array<main.Reminder>>;

export function GetUpcomingReminders():Promise<Array<main.Reminder>>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartBackgroundWorker():Promise<void>;

export function TestNotification():Promise<string>;
