// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllNotifications():Promise<Array<main.Reminder>>;

export function GetLowStockAlerts():Promise<Array<main.Reminder>>;

export function GetUpcomingReminders():Promise<Array<main.Reminder>>;
