// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndNotify() {
  return window['go']['main']['NotificationService']['CheckAndNotify']();
}

export function GetAllNotifications() {
  return window['go']['main']['NotificationService']['GetAllNotifications']();
}

export function GetLowStockAlerts() {
  return window['go']['main']['NotificationService']['GetLowStockAlerts']();
}

export function GetUpcomingReminders() {
  return window['go']['main']['NotificationService']['GetUpcomingReminders']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['NotificationService']['Notify'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['NotificationService']['SetContext'](arg1);
}

export function StartBackgroundWorker() {
  return window['go']['main']['NotificationService']['StartBackgroundWorker']();
}

export function TestNotification() {
  return window['go']['main']['NotificationService']['TestNotification']();
}
