// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllNotifications() {
  return window['go']['main']['NotificationService']['GetAllNotifications']();
}

export function GetLowStockAlerts() {
  return window['go']['main']['NotificationService']['GetLowStockAlerts']();
}

export function GetUpcomingReminders() {
  return window['go']['main']['NotificationService']['GetUpcomingReminders']();
}
