// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindPhotos(arg1, arg2, arg3) {
  return window['go']['main']['PhotoService']['BindPhotos'](arg1, arg2, arg3);
}

export function DeletePhoto(arg1) {
  return window['go']['main']['PhotoService']['DeletePhoto'](arg1);
}

export function GetPhotoBase64(arg1) {
  return window['go']['main']['PhotoService']['GetPhotoBase64'](arg1);
}

export function GetPhotos(arg1, arg2) {
  return window['go']['main']['PhotoService']['GetPhotos'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['PhotoService']['SetContext'](arg1);
}

export function UploadPhoto(arg1, arg2, arg3) {
  return window['go']['main']['PhotoService']['UploadPhoto'](arg1, arg2, arg3);
}
