// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function BindPhotos(arg1:string,arg2:number,arg3:number):Promise<void>;

export function DeletePhoto(arg1:number):Promise<void>;

export function GetPhotoBase64(arg1:number):Promise<string>;

export function GetPhotos(arg1:string,arg2:number):Promise<Array<main.Photo>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UploadPhoto(arg1:string,arg2:number,arg3:string):Promise<main.Photo>;
