// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['UpdateService']['ApplyUpdate']();
}

export function CheckForUpdates() {
  return window['go']['main']['UpdateService']['CheckForUpdates']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['UpdateService']['DownloadUpdate'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['UpdateService']['GetCurrentVersion']();
}

export function GetDownloadProgress() {
  return window['go']['main']['UpdateService']['GetDownloadProgress']();
}

export function GetPlatformInfo() {
  return window['go']['main']['UpdateService']['GetPlatformInfo']();
}

export function RestartApp() {
  return window['go']['main']['UpdateService']['RestartApp']();
}
