// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function GetDownloadProgress():Promise<number>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function RestartApp():Promise<void>;
