// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetWeather():Promise<main.WeatherData>;

export function SaveWeatherLocation(arg1:number,arg2:number,arg3:string):Promise<void>;

export function SearchLocations(arg1:string):Promise<Array<main.SearchResult>>;
