// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWeather() {
  return window['go']['main']['WeatherService']['GetWeather']();
}

export function SaveWeatherLocation(arg1, arg2, arg3) {
  return window['go']['main']['WeatherService']['SaveWeatherLocation'](arg1, arg2, arg3);
}

export function SearchLocations(arg1) {
  return window['go']['main']['WeatherService']['SearchLocations'](arg1);
}
